name: MOS Emulator (6502)

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Build Essentials
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # 3. Compile the Program
      - name: Build the Emulator
        run: make mosemu

      # 4. Run the Executable
      - name: Run the program
        run: ./build/mosemu
